name = "Chemise"
uuid = "dce8f835-6e30-4030-88d5-a4861057530f"
authors = ["Alejandro Luque <aluque@iaa.es> and contributors"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
